<script lang="ts">
  import { _ } from 'svelte-i18n';
  import Input from '../ui/Input.svelte';
  import Textarea from '../ui/Textarea.svelte';
  import Stepper from '../ui/Stepper.svelte';
  import Button from '../ui/Button.svelte';
  import type { Session } from '../../lib/stores/sessions.svelte';
  import { today } from '../../lib/date';

  interface Props {
    initial?: Session | undefined;
    defaultNumber: number;
    /**
     * A recap draft compiled by `SessionRecapReview` (from Live Session's
     * "End Session" flow) — prefills the summary and, while the GM hasn't
     * touched it yet, shows a dismissible "auto-generated" pill above the
     * textarea. Only ever passed for a fresh session (never alongside
     * `initial`, which is for editing an existing logged session).
     */
    draft?: Omit<Session, 'id'> | undefined;
    onsave: (data: Omit<Session, 'id'>) => void;
    oncancel: () => void;
  }

  let { initial, defaultNumber, draft, onsave, oncancel }: Props = $props();

  let number = $state(initial?.number ?? draft?.number ?? defaultNumber);
  let date = $state(initial?.date ?? draft?.date ?? today());
  let title = $state(initial?.title ?? draft?.title ?? '');
  let summary = $state(initial?.summary ?? draft?.summary ?? '');

  // Captured once, at form-open time — deliberately not reactive to further
  // prop changes, since the pill's whole job is to reflect "have you edited
  // *this* draft yet", not to track a moving target.
  const generatedSummary = draft?.summary;
  let pillDismissed = $state(false);
  const showAutoGenPill = $derived(
    generatedSummary !== undefined && !pillDismissed && summary === generatedSummary,
  );

  const summaryFieldId = 'session-summary-field';

  $effect(() => {
    if (generatedSummary === undefined) return;
    // Put the cursor after the drafted bullets (the trailing blank line
    // `SessionRecapReview` leaves) so the GM can start typing straight away
    // instead of landing at the top of the textarea.
    const el = document.getElementById(summaryFieldId) as HTMLTextAreaElement | null;
    el?.focus();
    el?.setSelectionRange(el.value.length, el.value.length);
  });

  function handleSubmit(event: SubmitEvent) {
    event.preventDefault();
    if (!title.trim()) return;
    onsave({ number, date, title: title.trim(), summary: summary.trim() });
  }
</script>

<form onsubmit={handleSubmit} class="flex flex-col gap-[var(--sp-4)]">
  <div class="flex gap-[var(--sp-5)] items-end flex-wrap">
    <Stepper label={$_('sessions.form.number')} value={number} min={1} max={999} size="md" onchange={(v) => (number = v)} />
    <Input label={$_('sessions.form.date')} type="date" bind:value={date} />
  </div>
  <Input label={$_('sessions.form.title')} bind:value={title} required />
  <div class="flex flex-col gap-[var(--sp-2)]">
    {#if showAutoGenPill}
      <div
        class="flex items-center justify-between gap-[var(--sp-3)] py-1.5 px-3 rounded-[var(--radius-md)] bg-[var(--accent-tint)] text-[var(--accent)] text-[length:var(--text-sm)] font-[family-name:var(--font-body)]"
      >
        <span>{$_('sessions.form.autoGenerated')}</span>
        <button
          type="button"
          aria-label={$_('sessions.form.dismissAutoGenerated')}
          onclick={() => (pillDismissed = true)}
          class="shrink-0 leading-none text-[length:var(--text-body)] cursor-pointer"
        >
          &times;
        </button>
      </div>
    {/if}
    <Textarea
      id={summaryFieldId}
      label={$_('sessions.form.summary')}
      bind:value={summary}
      rows={5}
      placeholder={$_('sessions.form.summaryPlaceholder')}
    />
  </div>

  <div class="flex justify-end gap-[var(--gap-inline)] pt-[var(--sp-2)]">
    <Button type="button" variant="ghost" onclick={oncancel}>{$_('roster.form.cancel')}</Button>
    <Button type="submit" variant="primary">{$_('roster.form.save')}</Button>
  </div>
</form>
